# Generated by Django 6.1 on 2026-08-13 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('author_name', models.CharField(blank=True, max_length=200, verbose_name='Nom de la personne')),
                ('kind', models.CharField(choices=[('beneficiary', 'Bénéficiaire'), ('donor', 'Donateur'), ('partner', 'Partenaire'), ('volunteer', 'Bénévole')], default='beneficiary', max_length=20, verbose_name='Profil')),
                ('role_or_relation', models.CharField(blank=True, max_length=200, verbose_name="Rôle / lien avec l'organisation")),
                ('content', models.TextField(verbose_name='Témoignage')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publié')),
                ('publication_authorized', models.BooleanField(default=False, help_text='Obligatoire pour les témoignages de bénéficiaires (§30).', verbose_name='Autorisation de publication (écrite)')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Validé le')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.mediaitem', verbose_name='Photo (optionnelle)')),
                ('related_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project', verbose_name='Projet lié')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'témoignage',
                'verbose_name_plural': 'témoignages',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
