# Generated by Django 6.1 on 2026-08-13 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('code', models.SlugField(max_length=40, unique=True, verbose_name='Code')),
                ('color', models.CharField(default='#f59e0b', max_length=7, verbose_name='Couleur (hex)')),
            ],
            options={
                'verbose_name': 'statut de projet',
                'verbose_name_plural': 'statuts de projet',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('title', models.CharField(max_length=300, verbose_name='Titre')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Localisation')),
                ('context', models.TextField(blank=True, verbose_name='Contexte')),
                ('problem', models.TextField(blank=True, verbose_name='Problème')),
                ('objectives', models.TextField(blank=True, verbose_name='Objectifs')),
                ('beneficiaries', models.TextField(blank=True, verbose_name='Bénéficiaires')),
                ('activities', models.TextField(blank=True, verbose_name='Activités')),
                ('results', models.TextField(blank=True, verbose_name='Résultats')),
                ('progress_percent', models.PositiveSmallIntegerField(default=0, verbose_name='Progression (%)')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Budget')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Devise')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Projet à la une')),
                ('publication_authorized', models.BooleanField(default=False, help_text='Autorisation écrite de publication des photos/bénéficiaires (§30).', verbose_name='Publication autorisée')),
                ('needs_donation', models.BooleanField(default=False, verbose_name='Accepte les dons ciblés')),
                ('seo_description', models.CharField(blank=True, max_length=300, verbose_name='Description SEO')),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_cover', to='media.mediaitem', verbose_name='Image de couverture')),
                ('gallery', models.ManyToManyField(blank=True, related_name='projects', to='media.mediaitem', verbose_name='Galerie')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='programs.program', verbose_name='Programme')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='projects.projectstatus', verbose_name='Statut')),
            ],
            options={
                'verbose_name': 'projet',
                'verbose_name_plural': 'projets',
                'ordering': ['-start_date', 'title'],
                'indexes': [models.Index(fields=['status', 'start_date'], name='projects_pr_status__c35bcb_idx')],
            },
        ),
    ]
