# Generated by Django 6.1 on 2026-09-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='views',
            field=models.PositiveBigIntegerField(default=0, editable=False, verbose_name='Vues'),
        ),
    ]
