# Generated by Django 6.1 on 2026-08-13 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('kind', models.CharField(choices=[('audit', 'Audit'), ('import', 'Import'), ('report', 'Rapport')], default='import', max_length=20, verbose_name='Type')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Démarré le')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminé le')),
                ('status', models.CharField(choices=[('RUNNING', 'En cours'), ('SUCCESS', 'Réussi'), ('FAILED', 'Échoué')], default='RUNNING', max_length=20, verbose_name='Statut')),
                ('log', models.TextField(blank=True, verbose_name='Journal')),
            ],
            options={
                'verbose_name': 'exécution de migration',
                'verbose_name_plural': 'exécutions de migration',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='URLMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_url', models.URLField(max_length=500, unique=True, verbose_name='Ancienne URL (WordPress)')),
                ('new_url', models.CharField(blank=True, max_length=500, verbose_name='Nouvelle URL (Django)')),
                ('mapped_at', models.DateTimeField(auto_now=True, verbose_name='Mappé le')),
            ],
            options={
                'verbose_name': "correspondance d'URL",
                'verbose_name_plural': "correspondances d'URL",
            },
        ),
        migrations.CreateModel(
            name='ImportedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('source_type', models.CharField(choices=[('post', 'Article'), ('page', 'Page'), ('media', 'Média'), ('category', 'Catégorie'), ('tag', 'Étiquette')], max_length=20, verbose_name='Type source')),
                ('source_id', models.CharField(max_length=40, verbose_name='ID source')),
                ('source_title', models.CharField(blank=True, max_length=300, verbose_name='Titre source')),
                ('source_url', models.URLField(blank=True, max_length=500, verbose_name='URL source')),
                ('destination_model', models.CharField(blank=True, max_length=100, verbose_name='Modèle destination')),
                ('destination_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='ID destination')),
                ('status', models.CharField(choices=[('IMPORTED', 'Importé'), ('SKIPPED', 'Ignoré'), ('ERROR', 'Erreur')], default='IMPORTED', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='migration.migrationrun', verbose_name='Exécution')),
            ],
            options={
                'verbose_name': 'élément importé',
                'verbose_name_plural': 'éléments importés',
                'unique_together': {('run', 'source_type', 'source_id')},
            },
        ),
    ]
