# Generated by Django 6.1 on 2026-08-13 09:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Nom complet')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Pays')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Don anonyme')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Donateur mensuel')),
                ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
            ],
            options={
                'verbose_name': 'donateur',
                'verbose_name_plural': 'donateurs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('reference', models.CharField(blank=True, editable=False, max_length=30, unique=True, verbose_name='Référence (reçu)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Devise')),
                ('frequency', models.CharField(choices=[('once', 'Don unique'), ('monthly', 'Don mensuel')], default='once', max_length=10, verbose_name='Fréquence')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PROCESSING', 'En traitement'), ('SUCCEEDED', 'Réussi'), ('FAILED', 'Échoué'), ('REFUNDED', 'Remboursé'), ('CANCELLED', 'Annulé')], db_index=True, default='PENDING', max_length=12, verbose_name='Statut')),
                ('provider_reference', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Référence fournisseur')),
                ('idempotency_key', models.CharField(editable=False, help_text='Anti-double paiement (§19).', max_length=100, unique=True, verbose_name="Clé d'idempotence")),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Don anonyme')),
                ('donor_message', models.TextField(blank=True, verbose_name='Message du donateur')),
                ('receipt_pdf', models.FileField(blank=True, upload_to='receipts/%Y/%m/', verbose_name='Reçu PDF')),
                ('receipt_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Email de remerciement envoyé le')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Payé le')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='projects.project', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'don',
                'verbose_name_plural': 'dons',
                'ordering': ['-created_at'],
            },
        ),
    ]
