# Generated by Django 6.1 on 2026-08-13 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donations', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.paymentprovider', verbose_name='Passerelle'),
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['email'], name='donations_d_email_16156b_idx'),
        ),
        migrations.AddField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='donations.donor', verbose_name='Donateur'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['status'], name='donations_d_status_73ca83_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['created_at'], name='donations_d_created_26bd74_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['currency', 'amount'], name='donations_d_currenc_a53a25_idx'),
        ),
    ]
