# Generated by Django 6.1 on 2026-09-24 07:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransferConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse e-mail')),
                ('country', models.CharField(max_length=100, verbose_name='Pays')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Montant envoyé')),
                ('currency', models.CharField(choices=[('USD', 'USD ($)'), ('EUR', 'EUR (€)'), ('CDF', 'CDF (FC)'), ('GBP', 'GBP (£)'), ('CAD', 'CAD ($)'), ('CHF', 'CHF'), ('Other', 'Autre')], default='USD', max_length=10, verbose_name='Devise')),
                ('transfer_date', models.DateField(verbose_name='Date du virement')),
                ('transaction_reference', models.CharField(db_index=True, max_length=120, verbose_name='N° / référence de transaction')),
                ('proof', models.FileField(blank=True, help_text='Reçu bancaire, capture d’écran ou PDF (5 Mo max).', upload_to='donations/bank_transfers/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg', 'webp'])], verbose_name='Preuve de paiement')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('verified', 'Vérifié'), ('rejected', 'Rejeté')], db_index=True, default='pending', max_length=12, verbose_name='Statut')),
                ('admin_note', models.TextField(blank=True, verbose_name='Note interne (admin)')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Vérifié le')),
                ('donation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transfers', to='donations.donation', verbose_name='Don lié')),
            ],
            options={
                'verbose_name': 'confirmation de virement',
                'verbose_name_plural': 'Virements bancaires',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='donations_b_status_d2e77d_idx'), models.Index(fields=['country'], name='donations_b_country_8551bd_idx'), models.Index(fields=['transfer_date'], name='donations_b_transfe_a1a28b_idx')],
            },
        ),
    ]
