# Generated by Django 6.1 on 2026-09-24 07:29

import django.core.files.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_banktransferconfirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransferconfirmation',
            name='proof',
            field=models.FileField(blank=True, help_text='Reçu bancaire, capture d’écran ou PDF (5 Mo max).', storage=django.core.files.storage.FileSystemStorage(location='F:\\SITE DE LA MISERICORDE\\citedelamisericorde\\private\\bank_transfers'), upload_to='%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg', 'webp'])], verbose_name='Preuve de paiement'),
        ),
    ]
