# Generated by Django 6.1 on 2026-08-13 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('label', models.CharField(help_text='Ex. : Enfants accompagnés', max_length=200, verbose_name='Libellé')),
                ('value', models.PositiveBigIntegerField(verbose_name='Valeur')),
                ('prefix', models.CharField(blank=True, default='+', max_length=10, verbose_name='Préfixe (ex. +)')),
                ('suffix', models.CharField(blank=True, max_length=10, verbose_name='Suffixe (ex. %)')),
                ('icon', models.CharField(blank=True, max_length=80, verbose_name='Icône (classe CSS)')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
                ('source', models.CharField(blank=True, help_text='Référence obligatoire : rapport, audit, validation humaine…', max_length=300, verbose_name='Source du chiffre')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': "indicateur d'impact",
                'verbose_name_plural': "indicateurs d'impact",
                'ordering': ['sort_order'],
            },
        ),
    ]
