# Generated by Django 6.1 on 2026-08-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('subject', models.CharField(choices=[('general', 'Question générale'), ('donation', 'Faire un don'), ('partnership', 'Partenariat'), ('volunteering', 'Bénévolat'), ('press', 'Presse')], default='general', max_length=30, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lu le')),
                ('is_spam', models.BooleanField(db_index=True, default=False, verbose_name='Spam')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='Navigateur')),
            ],
            options={
                'verbose_name': 'message de contact',
                'verbose_name_plural': 'messages de contact',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_read'], name='contact_con_is_read_9a011e_idx'), models.Index(fields=['is_spam'], name='contact_con_is_spam_8ef3b9_idx')],
            },
        ),
    ]
