# Generated by Django 6.1 on 2026-08-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(default='Cité de la Miséricorde', max_length=200, verbose_name="Nom de l'organisation")),
                ('legal_name', models.CharField(blank=True, help_text='Ex. : Collectif des Jeunes pour la Paix et le Développement (CJPD) Asbl', max_length=200, verbose_name='Nom légal (ASBL)')),
                ('tagline', models.CharField(default='Heureux ceux qui procurent la paix', max_length=200, verbose_name='Slogan')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email général')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('address_bukavu', models.CharField(blank=True, max_length=300, verbose_name='Adresse Bukavu')),
                ('address_goma', models.CharField(blank=True, max_length=300, verbose_name='Adresse Goma')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('pinterest', models.URLField(blank=True, verbose_name='Pinterest')),
                ('twitter', models.URLField(blank=True, verbose_name='X / Twitter')),
                ('youtube', models.URLField(blank=True, verbose_name='YouTube')),
                ('whatsapp', models.CharField(blank=True, max_length=50, verbose_name='WhatsApp')),
                ('map_embed_url', models.URLField(blank=True, verbose_name='URL carte (Leaflet/OSM)')),
                ('donation_currency', models.CharField(default='USD', max_length=3, verbose_name='Devise par défaut des dons')),
                ('pwa_theme_color', models.CharField(default='#0f766e', max_length=7, verbose_name='Couleur thème PWA')),
                ('google_analytics_id', models.CharField(blank=True, max_length=50, verbose_name='Google Analytics (GA4)')),
                ('matomo_url', models.URLField(blank=True, verbose_name='Matomo URL')),
                ('matomo_site_id', models.CharField(blank=True, max_length=20, verbose_name='Matomo Site ID')),
                ('recaptcha_site_key', models.CharField(blank=True, max_length=100, verbose_name='reCAPTCHA v3 site key')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='Mode maintenance')),
            ],
            options={
                'verbose_name': 'paramètres du site',
                'verbose_name_plural': 'paramètres du site',
            },
        ),
    ]
