# Generated by Django 6.1 on 2026-08-13 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('code', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('mobile_money', 'Mobile Money (Flutterwave / Airtel / M-Pesa / Orange)'), ('other', 'Autre fournisseur')], max_length=30, unique=True, verbose_name='Code')),
                ('is_active', models.BooleanField(default=False, verbose_name='Actif')),
                ('supported_currencies', models.CharField(default='USD', max_length=100, verbose_name='Devises supportées (séparées par des virgules)')),
                ('supported_countries', models.CharField(blank=True, help_text='Vérifier la disponibilité pour la RDC avant activation (§18).', max_length=200, verbose_name='Pays supportés (ISO, séparés par des virgules)')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('logo', models.ImageField(blank=True, upload_to='payments/logos/', verbose_name='Logo')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Description affichée au donateur')),
            ],
            options={
                'verbose_name': 'passerelle de paiement',
                'verbose_name_plural': 'passerelles de paiement',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Devise')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PROCESSING', 'En traitement'), ('SUCCEEDED', 'Réussi'), ('FAILED', 'Échoué'), ('REFUNDED', 'Remboursé'), ('CANCELLED', 'Annulé')], db_index=True, default='PENDING', max_length=12, verbose_name='Statut')),
                ('provider_transaction_id', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='ID transaction fournisseur')),
                ('raw_response', models.JSONField(blank=True, default=dict, verbose_name='Réponse brute (fournisseur)')),
                ('error_message', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('attempted_at', models.DateTimeField(blank=True, null=True, verbose_name='Tentative le')),
                ('succeeded_at', models.DateTimeField(blank=True, null=True, verbose_name='Réussi le')),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='donations.donation', verbose_name='Don')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.paymentprovider', verbose_name='Passerelle')),
            ],
            options={
                'verbose_name': 'transaction de paiement',
                'verbose_name_plural': 'transactions de paiement',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='payments_pa_status_b6726a_idx'), models.Index(fields=['provider', 'status'], name='payments_pa_provide_1199a9_idx')],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('event_id', models.CharField(db_index=True, max_length=255, verbose_name='ID événement fournisseur')),
                ('event_type', models.CharField(max_length=100, verbose_name="Type d'événement")),
                ('payload', models.JSONField(default=dict, verbose_name='Payload')),
                ('signature_valid', models.BooleanField(default=False, verbose_name='Signature vérifiée')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Traité')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Traité le')),
                ('error_message', models.TextField(blank=True, verbose_name='Erreur de traitement')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.paymentprovider', verbose_name='Passerelle')),
            ],
            options={
                'verbose_name': 'événement webhook',
                'verbose_name_plural': 'événements webhook',
                'ordering': ['-created_at'],
                'unique_together': {('provider', 'event_id')},
            },
        ),
    ]
