# Generated by Django 6.1 on 2026-08-13 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('domain', models.CharField(choices=[('children', 'Enfants vulnérables'), ('women', 'Autonomisation des femmes'), ('humanitarian', 'Assistance humanitaire'), ('community', 'Développement communautaire')], max_length=30, unique=True, verbose_name='Domaine')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='Résumé (une phrase)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, max_length=80, verbose_name='Icône (classe CSS)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.mediaitem', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'programme',
                'verbose_name_plural': 'programmes',
                'ordering': ['order', 'title'],
            },
        ),
    ]
