# Generated by Django 6.1 on 2026-08-13 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nom complet')),
                ('role', models.CharField(max_length=160, verbose_name='Fonction')),
                ('formation', models.CharField(blank=True, max_length=220, verbose_name='Formation')),
                ('bio', models.TextField(blank=True, verbose_name='Biographie')),
                ('photo', models.ImageField(blank=True, upload_to='team/', verbose_name='Photo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
            ],
            options={
                'verbose_name': "Membre de l'équipe",
                'verbose_name_plural': "Membres de l'équipe",
                'ordering': ['order', 'id'],
            },
        ),
    ]
