# Generated by Django 6.1 on 2026-08-13 09:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=120, verbose_name='Nom')),
            ],
            options={
                'verbose_name': "catégorie d'article",
                'verbose_name_plural': "catégories d'articles",
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=80, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'étiquette',
                'verbose_name_plural': 'étiquettes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('title', models.CharField(max_length=300, verbose_name='Titre')),
                ('excerpt', models.TextField(blank=True, verbose_name='Extrait')),
                ('content', models.TextField(blank=True, help_text="Le HTML est nettoyé à l'enregistrement.", verbose_name='Contenu (HTML purifié)')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('archived', 'Archivé')], db_index=True, default='draft', max_length=20, verbose_name='Statut')),
                ('published_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Date de publication')),
                ('is_featured', models.BooleanField(default=False, verbose_name='À la une')),
                ('allow_comments', models.BooleanField(default=False, verbose_name='Commentaires autorisés')),
                ('publication_authorized', models.BooleanField(default=False, help_text='Autorisation écrite de publication des photos/enfants (§30).', verbose_name='Publication autorisée')),
                ('meta_title', models.CharField(blank=True, max_length=160, verbose_name='Meta title (SEO)')),
                ('meta_description', models.CharField(blank=True, max_length=300, verbose_name='Meta description (SEO)')),
                ('canonical_url', models.URLField(blank=True, verbose_name='URL canonique')),
                ('views', models.PositiveBigIntegerField(default=0, editable=False, verbose_name='Vues')),
                ('reading_time_minutes', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Temps de lecture (min)')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_cover', to='media.mediaitem', verbose_name='Image à la une')),
                ('related_images', models.ManyToManyField(blank=True, related_name='articles', to='media.mediaitem', verbose_name="Galerie d'images")),
                ('categories', models.ManyToManyField(blank=True, to='articles.articlecategory', verbose_name='Catégories')),
                ('tags', models.ManyToManyField(blank=True, to='articles.articletag', verbose_name='Étiquettes')),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['status', 'published_at'], name='articles_ar_status_7759bd_idx'), models.Index(fields=['slug'], name='articles_ar_slug_452037_idx')],
            },
        ),
    ]
