# Generated by Django 6.1 on 2026-08-13 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'catégorie de média',
                'verbose_name_plural': 'catégories de médias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('file', models.FileField(upload_to='media/%Y/%m/', verbose_name='Fichier')),
                ('kind', models.CharField(choices=[('image', 'Image'), ('document', 'Document')], default='image', max_length=20, verbose_name='Type')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('alt_text', models.CharField(blank=True, max_length=300, verbose_name='Texte alternatif (alt)')),
                ('checksum', models.CharField(blank=True, db_index=True, max_length=64, unique=True, verbose_name='Empreinte SHA-256')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Largeur (px)')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Hauteur (px)')),
                ('source_url', models.URLField(blank=True, help_text='Laisse vide si le média est natif.', verbose_name="URL d'origine (WordPress)")),
                ('taken_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de prise de vue')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.mediacategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'média',
                'verbose_name_plural': 'médias',
                'ordering': ['-created_at'],
            },
        ),
    ]
