# Generated by Django 6.1 on 2026-08-13 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publiée')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
                ('cover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.mediaitem', verbose_name='Image de couverture')),
            ],
            options={
                'verbose_name': 'galerie',
                'verbose_name_plural': 'galeries',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('caption', models.CharField(blank=True, max_length=300, verbose_name='Légende')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Position')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gallery.gallery', verbose_name='Galerie')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.mediaitem', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'image de galerie',
                'verbose_name_plural': 'images de galerie',
                'ordering': ['position'],
                'unique_together': {('gallery', 'media')},
            },
        ),
    ]
