# Generated by Django 6.1 on 2026-09-23 09:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('title', models.CharField(max_length=300, verbose_name='Titre')),
                ('excerpt', models.CharField(blank=True, max_length=400, verbose_name='Extrait')),
                ('content', models.TextField(blank=True, verbose_name='Contenu (texte)')),
                ('button_text', models.CharField(blank=True, max_length=80, verbose_name='Texte du bouton')),
                ('button_url', models.CharField(blank=True, help_text='URL interne (ex. /projets/) ou externe (https://…).', max_length=300, verbose_name='Lien du bouton')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié')], db_index=True, default='draft', max_length=20, verbose_name='Statut')),
                ('published_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Date de publication')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_posts', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_posts', to='media.mediaitem', verbose_name='Image')),
            ],
            options={
                'verbose_name': "publication d'accueil",
                'verbose_name_plural': "publications d'accueil",
                'ordering': ['order', '-published_at'],
                'indexes': [models.Index(fields=['status', 'published_at'], name='adminpanel__status_790442_idx')],
            },
        ),
    ]
