# Generated by Django 6.1 on 2026-08-13 09:33

import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Nom')),
                ('token', models.CharField(default=secrets.token_urlsafe, editable=False, max_length=64, unique=True, verbose_name='Jeton de désinscription')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Confirmé')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmé le')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True, verbose_name='Désinscrit le')),
                ('source', models.CharField(blank=True, max_length=100, verbose_name="Origine de l'inscription")),
            ],
            options={
                'verbose_name': 'abonné',
                'verbose_name_plural': 'abonnés',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active'], name='newsletter__is_acti_b7fe03_idx')],
            },
        ),
    ]
