# Generated by Django 6.1 on 2026-08-13 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('content', models.TextField(blank=True, verbose_name='Contenu (HTML purifié)')),
                ('template', models.CharField(blank=True, help_text="Nom du gabarit Django (ex. 'about.html'), vide pour le gabarit par défaut.", max_length=80, verbose_name='Gabarit')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié')], default='draft', max_length=20, verbose_name='Statut')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
                ('in_menu', models.BooleanField(default=False, verbose_name='Visible dans le menu')),
                ('meta_title', models.CharField(blank=True, max_length=160, verbose_name='Meta title (SEO)')),
                ('meta_description', models.CharField(blank=True, max_length=300, verbose_name='Meta description (SEO)')),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.mediaitem', verbose_name='Image de couverture')),
            ],
            options={
                'verbose_name': 'page',
                'verbose_name_plural': 'pages',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('title', models.CharField(max_length=250, verbose_name='Titre')),
                ('kind', models.CharField(choices=[('annual', 'Rapport annuel'), ('project', 'Rapport de projet'), ('financial', 'Rapport financier'), ('other', 'Autre document')], default='annual', max_length=20, verbose_name='Type')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Année')),
                ('document', models.FileField(upload_to='reports/%Y/', verbose_name='Fichier PDF')),
                ('summary', models.TextField(blank=True, verbose_name='Résumé')),
                ('is_published', models.BooleanField(default=False, help_text="Tout document doit être validé par l'administration avant publication (§31).", verbose_name='Publié')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Validé le')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Publié le')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'rapport / document',
                'verbose_name_plural': 'rapports / documents',
                'ordering': ['-year', 'title'],
            },
        ),
    ]
