# Generated by Django 6.1 on 2026-08-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('date', models.DateField(unique=True, verbose_name='Date')),
                ('visits', models.PositiveIntegerField(default=0, verbose_name='Visites')),
                ('unique_visitors', models.PositiveIntegerField(default=0, verbose_name='Visiteurs uniques')),
                ('top_pages', models.JSONField(blank=True, default=dict, verbose_name='Pages les plus vues')),
            ],
            options={
                'verbose_name': 'statistique quotidienne',
                'verbose_name_plural': 'statistiques quotidiennes',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('path', models.CharField(db_index=True, max_length=500, verbose_name='Chemin')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Pays (via GeoIP, optionnel)')),
                ('referrer', models.CharField(blank=True, max_length=500, verbose_name='Origine (referrer)')),
                ('is_bot', models.BooleanField(default=False, verbose_name='Robot détecté')),
            ],
            options={
                'verbose_name': 'vue de page',
                'verbose_name_plural': 'vues de pages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='analytics_p_created_4c2b45_idx'), models.Index(fields=['path', 'created_at'], name='analytics_p_path_53ae0e_idx')],
            },
        ),
    ]
