# Generated by Django 6.1 on 2026-09-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageview',
            name='visitor_key',
            field=models.CharField(blank=True, db_index=True, help_text='Hash IP+UA pour visiteurs uniques (pas d’IP en clair).', max_length=64, verbose_name='Visiteur (hash)'),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='country',
            field=models.CharField(blank=True, db_index=True, help_text='Via GeoIP2 si configuré, sinon Accept-Language.', max_length=100, verbose_name='Pays'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['country', 'created_at'], name='analytics_p_country_f28d6f_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['visitor_key', 'created_at'], name='analytics_p_visitor_126a77_idx'),
        ),
    ]
